name: GPT Workflow

on: [push]

jobs:
  gpt_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Execute GPT Plugin
      env:
        PLUGIN_APIKEY: ${{ secrets.GPT_API_KEY }}
      run: |
        docker run --rm -e PLUGIN_APIKEY=$PLUGIN_APIKEY sidharth14/gpt

