name: Print GITHUB_WORKSPACE

on:
  push:
    branches:
      - main

jobs:
  print-workspace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run JavaScript
      run: node index.js
